version: "3.9"

services:
  bot:
    image: ghcr.io/yokasashii/platinethemall-bot:latest
    secrets:
      - source: pta-bot-token
        target: discord_token
    volumes:
      - type: bind
        source: /home/skyvence/infra/service/pta-bot/teams.json
        target: /app/teams.json
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
        monitor: 30s
      labels:
        - "shepherd.enable=true"
        - "shepherd.auth.config=default"
    networks: [pta-net]

networks:
  pta-net:
    driver: overlay
    attachable: true

secrets:
  pta-bot-token:
    external: true
